project_name    = "estudio-platform"
environment     = "prod"
aws_region      = "sa-east-1"
dr_region       = "us-east-1"
vpc_cidr        = "10.42.0.0/16"
db_name         = "estudioplatform"
container_image = "public.ecr.aws/docker/library/nginx:latest"
